### ISSUE TITLE
Version 2.2 throws NullReferenceException on attempt to update IP

### ISSUE THREAD

**Issue by leo-liar** [XWolfOverride/DuckDNS#6]
Hello there,

as titled, version 2.2 fails to update the IP and immediately throws the following error when trying to do so:
```
Error
Update of DuckDNS failed, check token and domain:
NullReferenceException: Der Objektverweis wurde nicht
auf eine Objektinstanz festgelegt.
```
(The German line translates to: `The object reference has not been set to an object instance.`)

There's been no change in my settings but I also deleted my *DuckDNS.cfg* file and entered my settings again to no avail.

**Comment by XWolfOverride** [comment]
Binary updated on v2.2, please check.

**Comment by leo-liar** [comment]
> Binary updated on v2.2, please check.

Yes, that fixed it! Thank you.
