### ISSUE TITLE
Windows Security Blocking Opening of v2.2

### ISSUE THREAD

**Issue by PMMi11er** [XWolfOverride/DuckDNS#7]
Similar to closed issue #5; opening the "DuckDNS.zip" file in Windows 10, Defender is blocking claiming the trojan "Oneeva.A!l is present.  It won't say which file in the package is infected.
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fOneeva.A!ml&threatid=2147729349

**Comment by XWolfOverride** [comment]
Hello I search for more information of this Oneeva and found this: https://drmalware.wiki/trojanscript-oneeva-aml/ (Sorry, spanish)

As I see this trojan is a visual basic script (VBS) malware. and there is no VBS files in the zip, not inside the exe, it is C# project.
Just updated my Windows defender 
![Screenshot 2021-05-01 at 10 30 47](https://user-images.githubusercontent.com/7501291/116776763-98b22880-aa6a-11eb-99a7-2e881441ef56.png)
download the last version of DuckDNS here and rescan the .zip, no problems found.

Please if you can do a manual update of the windows defender and check it again?

I upload also a 7zip DuckDNS version to see if there are less problems with that.

I do not understand why so many problems with this program, I supose it is suspicious for being a small program that fetch local ip and send it to a web service, but the trojans identified are totally random.

**Comment by PMMi11er** [comment]
It allows me to extract the exe file from the .7z, but finds another "virus" when I scan the exe.
I uploaded DuckDNS.exe from the 7z file to virustotal.com, and it reports 29 AV engines claim infection.
https://www.virustotal.com/gui/file/6ed7e96642288f048ddb05f32e9061c91ab830f4837db074c852646da8f23b7e/detection

I also uploaded the DuckDNS.zip and 23 engines say infection.
https://www.virustotal.com/gui/file/bb4ec2bb2e4e32e0f3c43e89fca0c239676df44d916ea9c9ae2fb7cbfa86baed/detection

The details and behavior tabs in the results may help explain why?

**Comment by XWolfOverride** [comment]
Hello, I do the check from virustotal from a fresh compiled file and I got the same result and also check all my computer with the Widnows defender with no issues. I sincerely think this are false positives from heuristics done in the program or fast checks with hash. The program is 90Kb in size and is difficult to have that 15-20 different threats in that small size.

I also check others of my programs from a fresh build with virustotal and does not found any problem.
It's funny that if I compile DuckDNS in debug mode, there is only 1 threat found in virustotal, and if y check the release version then there are 29. Same program with or without debug information inside.
And for the last point If y modify the way of generating the duckdns service URL there is no threats found.

For being completely sure and discard any small possiblitiy I recommend you to compile from sources and pass again the virustotal check, use the release mode if you want to check the same uploaded version.

I will upload changes done in URL generation and update the reelase.

**Comment by PMMi11er** [comment]
Thank you for looking into this.  I'll go the compile route.
